---
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          # specify the `main` branch as the remote branch to push to
          branch: 'master'
          git_remote_url: 'ssh://dokku@server-populate04.populate.tools/~/decidim-terrassa'
          ssh_private_key: ${{ secrets.DOKKU_DEPLOY_SSH_KEY }}
